name: LLRT Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      fail-fast: ${{ startsWith(github.ref, 'refs/tags/') }}
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x86_64
            release: x64
            toolchain: nightly-x86_64-pc-windows-gnu

    uses: ./.github/workflows/build.yml
    with:
      os: ${{ matrix.os }}
      platform: ${{ matrix.platform }}
      arch: ${{ matrix.arch }}
      release: ${{ matrix.release }}
      toolchain: ${{ matrix.toolchain }}
  release:
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./CHANGELOG.md
          preserve_order: true
          prerelease: contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'rc')
          files: |
            ./llrt-windows-x64.zip
            ./llrt-windows-x64-no-sdk.zip
            ./llrt-windows-x64-full-sdk.zip
  publish:
    needs:
      - build
    uses: ./.github/workflows/publish.yml
    with:
      ref: ${{ github.ref }}
    secrets:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
